/**
 * PDF generation — overlay filled text on a scanned form image or PDF.
 * Uses pdf-lib for layout. Standard fonts handle Latin text only;
 * non-Latin field values are skipped in overlay mode (use summary mode).
 */

import { PDFDocument, PDFPage, rgb, StandardFonts } from "pdf-lib";

export interface FilledField {
  label: string;
  value: string;
  /** X position as percentage of page width (0-100) */
  x: number;
  /** Y position as percentage of page height (0-100) */
  y: number;
  /** Width as percentage of page width */
  width: number;
  /** Height as percentage of page height */
  height: number;
}

/**
 * Generate a PDF with the original form as background and filled values overlaid.
 * Handles both image inputs (JPEG/PNG) and PDF inputs.
 */
export async function generateFilledPdf(
  formBase64: string,
  filledFields: FilledField[],
): Promise<string> {
  const base64Data = formBase64.includes(",")
    ? formBase64.split(",")[1]!
    : formBase64;
  const rawBytes = Buffer.from(base64Data, "base64");

  const isPdf =
    formBase64.includes("application/pdf") ||
    rawBytes.slice(0, 5).toString() === "%PDF-";
  const isJpeg =
    formBase64.includes("image/jpeg") ||
    formBase64.includes("image/jpg") ||
    (rawBytes[0] === 0xff && rawBytes[1] === 0xd8);
  const isPng =
    formBase64.includes("image/png") ||
    (rawBytes[0] === 0x89 && rawBytes[1] === 0x50);

  let pdfDoc: PDFDocument;
  let page: PDFPage;
  let pageWidth: number;
  let pageHeight: number;

  if (isPdf) {
    // Input is a PDF — copy the first page as background
    const srcDoc = await PDFDocument.load(rawBytes);
    pdfDoc = await PDFDocument.create();
    const [copiedPage] = await pdfDoc.copyPages(srcDoc, [0]);
    pdfDoc.addPage(copiedPage);
    page = pdfDoc.getPage(0);
    const { width, height } = page.getSize();
    pageWidth = width;
    pageHeight = height;
  } else {
    // Input is an image — embed as background
    pdfDoc = await PDFDocument.create();
    let image;
    if (isPng) {
      image = await pdfDoc.embedPng(rawBytes);
    } else if (isJpeg) {
      image = await pdfDoc.embedJpg(rawBytes);
    } else {
      // Try JPEG as default
      image = await pdfDoc.embedJpg(rawBytes);
    }

    pageWidth = 595.28; // A4
    const scale = pageWidth / image.width;
    pageHeight = image.height * scale;
    page = pdfDoc.addPage([pageWidth, pageHeight]);
    page.drawImage(image, { x: 0, y: 0, width: pageWidth, height: pageHeight });
  }

  // Overlay filled text
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontSize = 10;
  const HAS_NON_LATIN = /[^\u0000-\u007F]/;

  for (const field of filledFields) {
    if (!field.value) continue;
    if (HAS_NON_LATIN.test(field.value)) continue;

    const x = (field.x / 100) * pageWidth + 2;
    const y = pageHeight - (field.y / 100) * pageHeight - fontSize - 2;

    try {
      page.drawText(field.value, {
        x,
        y,
        size: fontSize,
        font,
        color: rgb(0, 0, 0.6),
      });
    } catch {
      // Skip unrenderable characters
    }
  }

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes).toString("base64");
}

/**
 * Generate a clean summary PDF with field-value pairs.
 * Fallback when overlay positioning is unreliable or text is non-Latin.
 */
export async function generateSummaryPdf(
  filledFields: Record<string, string>,
  title: string,
): Promise<string> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let activePage: PDFPage = pdfDoc.addPage([595.28, 841.89]);
  let y = activePage.getSize().height - 50;

  activePage.drawText(title, {
    x: 50, y, size: 16, font: boldFont, color: rgb(0, 0.3, 0),
  });
  y -= 30;

  activePage.drawText("Generated by FormSaathi", {
    x: 50, y, size: 9, font, color: rgb(0.5, 0.5, 0.5),
  });
  y -= 25;

  for (const [label, value] of Object.entries(filledFields)) {
    if (y < 60) {
      activePage = pdfDoc.addPage([595.28, 841.89]);
      y = activePage.getSize().height - 50;
    }

    activePage.drawText(`${label}:`, {
      x: 50, y, size: 10, font: boldFont, color: rgb(0.2, 0.2, 0.2),
    });

    activePage.drawText(value, {
      x: 250, y, size: 10, font, color: rgb(0, 0, 0),
    });

    y -= 20;
  }

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes).toString("base64");
}
