import { auth } from "@clerk/nextjs/server";
import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, PDFPage, rgb, StandardFonts } from "pdf-lib";

export async function POST(request: NextRequest) {
  const { userId } = await auth();
  if (!userId)
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  let body: {
    formImage?: string;
    filledFields?: Record<string, string>;
    fieldPositions?: Array<{
      label: string;
      x: number;
      y: number;
      width: number;
      height: number;
    }>;
    title?: string;
    mode?: "overlay" | "summary";
  };

  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  if (!body.filledFields || Object.keys(body.filledFields).length === 0) {
    return NextResponse.json(
      { error: "filledFields required" },
      { status: 400 },
    );
  }

  try {
    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    // Page 1: Copy original form if available
    if (body.formImage) {
      const base64Data = body.formImage.includes(",")
        ? body.formImage.split(",")[1]!
        : body.formImage;
      const rawBytes = Buffer.from(base64Data, "base64");

      const isPdf =
        body.formImage.includes("application/pdf") ||
        rawBytes.slice(0, 5).toString() === "%PDF-";

      try {
        if (isPdf) {
          const srcDoc = await PDFDocument.load(rawBytes);
          const pageCount = srcDoc.getPageCount();
          const indices = Array.from({ length: pageCount }, (_, i) => i);
          const copiedPages = await pdfDoc.copyPages(srcDoc, indices);
          for (const p of copiedPages) pdfDoc.addPage(p);
        } else {
          // Image — embed as first page
          const isJpeg =
            body.formImage.includes("image/jpeg") ||
            (rawBytes[0] === 0xff && rawBytes[1] === 0xd8);
          const image = isJpeg
            ? await pdfDoc.embedJpg(rawBytes)
            : await pdfDoc.embedPng(rawBytes);
          const pageWidth = 595.28;
          const scale = pageWidth / image.width;
          const pageHeight = image.height * scale;
          const page = pdfDoc.addPage([pageWidth, pageHeight]);
          page.drawImage(image, {
            x: 0,
            y: 0,
            width: pageWidth,
            height: pageHeight,
          });
        }
      } catch (embedErr) {
        console.error("[fill-pdf] Could not embed original form:", embedErr);
        // Continue — will still create summary page
      }
    }

    // Summary page: Clean filled field-value list
    const title = body.title ?? "Filled Form Summary — FormSaathi";
    let summaryPage: PDFPage = pdfDoc.addPage([595.28, 841.89]);
    let y = summaryPage.getSize().height - 50;

    summaryPage.drawText(title, {
      x: 50,
      y,
      size: 16,
      font: boldFont,
      color: rgb(0, 0.3, 0),
    });
    y -= 24;

    summaryPage.drawText("Generated by FormSaathi — print this alongside your form", {
      x: 50,
      y,
      size: 9,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });
    y -= 8;

    // Divider
    summaryPage.drawLine({
      start: { x: 50, y },
      end: { x: 545, y },
      thickness: 0.5,
      color: rgb(0.8, 0.8, 0.8),
    });
    y -= 20;

    const HAS_NON_LATIN = /[^\u0000-\u007F]/;

    /** Strip non-Latin characters from text so Helvetica can render it. */
    function latinSafe(text: string): string {
      // Try to extract English portion from bilingual labels like "आवेदक का नाम / Applicant Name"
      if (text.includes("/")) {
        const parts = text.split("/");
        const englishPart = parts.find((p) => !HAS_NON_LATIN.test(p.trim()));
        if (englishPart) return englishPart.trim();
      }
      // Fall back to stripping non-Latin chars
      return text.replace(/[^\u0000-\u007F]/g, "").replace(/\s+/g, " ").trim() || "Field";
    }

    const entries = Object.entries(body.filledFields).filter(
      ([, v]) => v && v !== "this" && v !== "True",
    );

    for (const [label, value] of entries) {
      if (y < 60) {
        summaryPage = pdfDoc.addPage([595.28, 841.89]);
        y = summaryPage.getSize().height - 50;
      }

      // Label — use Latin-safe version
      const safeLabel = latinSafe(label);
      summaryPage.drawText(safeLabel + ":", {
        x: 50,
        y,
        size: 10,
        font: boldFont,
        color: rgb(0.2, 0.2, 0.2),
      });

      // Value — also make Latin-safe
      const safeValue = HAS_NON_LATIN.test(value) ? latinSafe(value) || value.replace(/[^\u0000-\u007F]/g, "") : value;
      if (safeValue) {
        summaryPage.drawText(safeValue, {
          x: 280,
          y,
          size: 11,
          font,
          color: rgb(0, 0.15, 0.4),
        });
      }

      y -= 22;
    }

    // Footer on summary page
    y -= 10;
    if (y > 30) {
      summaryPage.drawText(
        "Use this summary to fill your physical form or verify auto-filled fields.",
        {
          x: 50,
          y,
          size: 8,
          font,
          color: rgb(0.5, 0.5, 0.5),
        },
      );
    }

    const pdfBytes = await pdfDoc.save();
    const pdfBase64 = Buffer.from(pdfBytes).toString("base64");

    return NextResponse.json({
      pdf: pdfBase64,
      filename: `formsaathi-filled-${Date.now()}.pdf`,
    });
  } catch (err) {
    console.error("[agent/fill-pdf]", err);
    return NextResponse.json(
      { error: "PDF generation failed", detail: String(err) },
      { status: 500 },
    );
  }
}
